# action.yml
name: 'krew-plugin-release'
description: 'automatically opens PR for upstream krew-index repo when you publish new release of your awesome plugin'
inputs:
  plugin-name: 
    description: 'plugin-name'
    required: true
  upstream-krew-index-owner:
    description: 'the owner of upstream krew-index repo'  
    required: false
  upstream-krew-index-repo-name:
    description: 'the owner of upstream krew-index repo'  
    required: false
runs:
  using: 'docker'
  image: 'docker://rajatjindal/krew-plugin-release:v0.0.27'
  args:
    - ${{ inputs.upstream-krew-index-owner }}
    - ${{ inputs.upstream-krew-index-repo-name }}
    - ${{ inputs.plugin-name }}

